### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by mmmarquez** [albe-rosado/create-proton-app#14]
Hello!

Not sure if this is related to create-proton-app or Proton or similar. I haven't been able to successfully create the starter project.

* Mac Os sierra
* NPM V5.6.0
* NODE 10
* NVM

My log below, any help / direction would be appreciated. 

Thanks

```bash
15221 verbose stack Error: libui-node@0.2.0 install: `libui-download && autogypi && npm run build`
15221 verbose stack Exit status 1
15221 verbose stack     at EventEmitter.<anonymous> (/Users/mmarquez/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
15221 verbose stack     at emitTwo (events.js:126:13)
15221 verbose stack     at EventEmitter.emit (events.js:214:7)
15221 verbose stack     at ChildProcess.<anonymous> (/Users/mmarquez/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
15221 verbose stack     at emitTwo (events.js:126:13)
15221 verbose stack     at ChildProcess.emit (events.js:214:7)
15221 verbose stack     at maybeClose (internal/child_process.js:925:16)
15221 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15222 verbose pkgid libui-node@0.2.0
15223 verbose cwd /Users/mmarquez/Downloads/proton-native-master 2/react-app
15224 verbose Darwin 16.6.0
15225 verbose argv "/Users/mmarquez/.nvm/versions/node/v8.9.4/bin/node" "/Users/mmarquez/.nvm/versions/node/v8.9.4/bin/npm" "install"
15226 verbose node v8.9.4
15227 verbose npm  v5.6.0
15228 error code ELIFECYCLE
15229 error errno 1
15230 error libui-node@0.2.0 install: `libui-download && autogypi && npm run build`
15230 error Exit status 1
15231 error Failed at the libui-node@0.2.0 install script.
15231 error This is probably not a problem with npm. There is likely additional logging output above.
15232 verbose exit [ 1, true ]
```

**Comment by mischnic** [comment]
> `"/Users/mmarquez/.nvm/versions/node/v8.9.4/bin/node"`

Seems like your's using Node v8.9.4. Should work though.

@parro-it

**Comment by albe-rosado** [comment]
Not to be annoying but @mmmarquez , do you have xcode installed?

**Comment by mmmarquez** [comment]
Not annoying -- @albe-rosado ! Thanks for the quick response --
XCode is installed (v8.3.2).

Possible to be an issue with nvm? I got this to run in my home computer (mac, sierra), which I don't use nvm (still couldn't package/build the app -- but one issue at the time).

**Comment by parro-it** [comment]
Can you post your node_modules/.bin content?

**Comment by mmmarquez** [comment]
@parro-it, here it is:  
![BIN](https://s7.postimg.cc/qji8ncjzf/Screen_Shot_2018-05-21_at_11.20.01_AM.png)

**Comment by parro-it** [comment]
It seems there are some binaries missing: both libui-download & autogypi.
Could you try to remove node_modules folder, npm install from scratch and verify the your .bin folder contains both libui-download & autogypi files?

**Comment by mmmarquez** [comment]
hey @parro-it --

- Removed node_modules
- Installed dependencies

Seems the process fails when trying to install those --

```bash
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.0 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
`.bin` folder is the same as the previous screenshot.

**Comment by mischnic** [comment]
Can you post your package.json file?

**Comment by mmmarquez** [comment]
@mischnic here it is! I haven't touched the file, this is what is generated when I initially run `create-proton-app`

```json
{
  "name": "react-app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/.bin/babel-node index.js",
    "build": "node_modules/.bin/babel index.js -d bin/",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "dependencies": {
    "proton-native": "latest"
  },
  "devDependencies": {
    "electron-builder": "latest",
    "babel-cli": "latest",
    "babel-preset-env": "latest",
    "babel-preset-stage-0": "latest",
    "babel-preset-react": "latest"
  },
  "build": {
    "protonNodeVersion": "current",
    "mac": {
      "identity": null
    }
  }
}
```

**Comment by parro-it** [comment]
Trying with the same package.json, it works fine for me (using macOS High Sierra and Node.js 10.1.0)
What node version are you really using?
You said Node 10 in the first post, but from the log:

```
/Users/mmarquez/.nvm/versions/node/v8.9.4/bin/node
```

It seems you are using some other release from nvm...

**Comment by mmmarquez** [comment]
@parro-it 

My mistake initially -- V8.9.4 was originally used, but even when changing the version -- the issue persists. Shouldn't it work with V8+ ?

Apologize for the questions -- and confusion.

```bash
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.0 install: `libui-download && autogypi && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mmarquez/.npm/_logs/2018-05-21T17_12_28_557Z-debug.log
```

Using 10 -- still fails, but might be a different issue. 

```bash
clang: error: no such file or directory: '2/react-app/node_modules/libui-node/src/includes'
clang: error: no such file or directory: '2/react-app/node_modules/libui-node'
make: *** [Release/obj.target/nbind/../nbind/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mmarquez/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Users/mmarquez/.nvm/versions/node/v10.0.0/bin/node" "/Users/mmarquez/.nvm/versions/node/v10.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/mmarquez/Downloads/proton-native-master 2/react-app/node_modules/libui-node
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libui-node@0.2.0 build: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libui-node@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by mischnic** [comment]
Please run it in a directory without a space in the name ("proton-native-master 2"). Should have said that earlier....

**Comment by parro-it** [comment]
@mischnic, I have the same idea, I'm testing now with a space in the path to see if I can reproduce the problem....

**Comment by mmmarquez** [comment]
Hey !  :) 

So -- that fixed the issue -- **install was succesful.** Sorry about that, didn't consider it to be an issue as it was not even the root directory -- but kind of makes sense due to the kind of project.

Many thanks!
