### ISSUE TITLE
create-proton-app doesn't works in Linux

### ISSUE THREAD

**Issue by paulcarroty** [albe-rosado/create-proton-app#20]
```
/home/paul/.node-gyp/11.0.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~

In file included from ../../nbind/include/nbind/api.h:78,
                 from ../../nbind/include/nbind/BindDefiner.h:11,
                 from ../../nbind/include/nbind/noconflict.h:8,
                 from ../../nbind/include/nbind/nbind.h:8,
                 from /home/paul/Projects/preact/my-app/node_modules/libui-node/src/includes/event-loop.h:6,
                 from ../src/EventLoop.cc:1:
../../nbind/include/nbind/v8/External.h: In static member function ‘static nbind::BindingType<nbind::External>::Type nbind::BindingType<nbind::External>::fromWireType(nbind::WireType)’:
../../nbind/include/nbind/v8/External.h:112:80: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
  static inline Type fromWireType(WireType arg) { return(External(arg->ToObject())); }
                                                                                ^

```

node 11.0, gcc 8.2.1.

**Comment by mischnic** [comment]
The part of the install logs you posted only contain a warning.
What do you mean by "doesn't work"?

CC @parro-it

**Comment by paulcarroty** [comment]
[npm.log](https://github.com/albe-rosado/create-proton-app/files/2523174/npm.log)

```
$ npm run start

> my-app@0.0.1 start /home/paul/Projects/preact/my-app
> babel-node index.js

/home/paul/Projects/preact/my-app/node_modules/nbind/dist/nbind.js:15
        throw (err);
        ^

Error: Could not locate the bindings file. Tried:
/home/paul/Projects/preact/my-app/node_modules/libui-node/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/build/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/build/Debug/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/build/Release/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/out/Debug/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/Debug/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/out/Release/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/Release/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/build/default/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/compiled/11.0.0/linux/x64/nbind.node
/home/paul/Projects/preact/my-app/node_modules/libui-node/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/build/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/build/Debug/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/build/Release/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/out/Debug/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/Debug/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/out/Release/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/Release/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/build/default/nbind.js
/home/paul/Projects/preact/my-app/node_modules/libui-node/compiled/11.0.0/linux/x64/nbind.js
    at findCompiledModule (/home/paul/Projects/preact/my-app/node_modules/nbind/dist/nbind.js:83:15)
    at find (/home/paul/Projects/preact/my-app/node_modules/nbind/dist/nbind.js:93:13)
    at Object.init (/home/paul/Projects/preact/my-app/node_modules/nbind/dist/nbind.js:104:5)
    at Object.<anonymous> (/home/paul/Projects/preact/my-app/node_modules/libui-node/index.js:5:23)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/paul/Projects/preact/my-app/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.1 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2018-10-28T20_28_06_231Z-debug.log

```
[2018-10-28T20_28_06_231Z-debug.log](https://github.com/albe-rosado/create-proton-app/files/2523176/2018-10-28T20_28_06_231Z-debug.log)

**Comment by mischnic** [comment]
Please try deleting the `node_modules` folder and rerunning `npm install`.
If it still doesn't work, check if the file `/home/paul/Projects/preact/my-app/node_modules/libui-node/nbind.node` exists.

**Comment by paulcarroty** [comment]
@mischnic got the test window. The compilation was 2m longer and `nbind.node` exists. Thank you. 

I also did the same on Ubuntu 14.04 (c9.io) and all works as expected. Maybe new Node broke something.

**Comment by mischnic** [comment]
Great!

I've noticed this happening after installing additional packages, because that somehow deleted these library files.
